name: Publish project to Maven repository
on: workflow_dispatch
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Cache Gradle dependencies
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle-

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
          
      - name: Set up gradle.properties
        env:
          GRADLE_PROPERTIES_BASE64_PROPERTIES: ${{ secrets.GRADLE_PROPERTIES_BASE64_PROPERTIES }}
        run: |
          mkdir -p ~/.gradle/
          echo "$GRADLE_PROPERTIES_BASE64_PROPERTIES" > ~/.gradle/gradle.properties.b64
          base64 -d -i ~/.gradle/gradle.properties.b64 > ~/.gradle/gradle.properties
        
      - name: Check gradle.properties
        run: cat ~/.gradle/gradle.properties
        
      - name: Publish with Gradle
        run: ./gradlew publishReleasePublicationToCexupRepository
      
      - name: Save Gradle dependencies cache
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
